[project]
name = "secom"
version = "0.1.0"
description = "UCI SECOM dataset analysis"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.9",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
    "seaborn>=0.13.2",
    "tabulate>=0.10.0",
    "uci-dataset>=0.0.7",
    "ucimlrepo>=0.0.7",
    "umap-learn>=0.5.12",
    "xgboost>=3.2.0",
]
